on:
  push:
    branches:
      - gh-pages
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.ACCESS_TOKEN }}
        run: yarn build

      - name: deploy
        uses: zungta/ghpages@v0.3.1
        env:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: 'public/'
          BRANCH: 'main'